# image used for testing is inherited from the SKA group variables
image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

stages:
  - lint
  - build
  - test
  - scan
  - publish
  - pages

# Standardised included jobs
variables:
  GIT_SUBMODULE_STRATEGY: recursive

include:

  # Python packages build, lint, test, and publish
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python.gitlab-ci.yml'

  # Release management
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'

  # Documentation
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

  # Create Gitlab CI badges from CI metrics
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'
